# Generated by Django 3.1.3 on 2020-11-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_comentcrm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentcrm',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
